#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse

# Import from scraping

from scraping import app

if __name__ == '__main__':
    usage = '%(prog)s'
    description = 'Package for scraping data from rakuten.co.jp'
    app.main()
    
